FROM docker.io/library/python@sha256:399babc8b49529dabfd9c922f2b5eea81d611e4512e3ed250d75bd2e7683f4b0

RUN apk add --no-cache ca-certificates wget
WORKDIR /app
COPY exporter.py /app/exporter.py

USER 65534:65534
EXPOSE 8080
ENTRYPOINT ["python3", "/app/exporter.py"]
